steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud alpha container bare-metal clusters enroll hybrid-cluster-01 \
    --project=hpe-managed-services \
    --location=asia-east1 \
    --admin-cluster-membership=projects/undefined/locations/global/memberships/undefined
