steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud services enable \
    --project hpe-managed-services \
    gkeonprem.googleapis.com
    
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container bare-metal clusters query-version-config \
    --project=hpe-managed-services \
    --location=asia-east1
    
    
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container bare-metal admin-clusters enroll hybrid-cluster-01 \
    --project=hpe-managed-services \
    --admin-cluster-membership=projects/hpe-managed-services/locations/global/memberships/hybrid-cluster-01 \
    --location=asia-east1