steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/hpe-managed-services/anthos-ci:$COMMIT_SHA', '.']
images: ['gcr.io/hpe-managed-services/anthos-ci:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'get'
  - 'pods'
  - '-A'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=registered'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hybrid-cluster-01'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hybrid-cluster-01'